### ISSUE TITLE
Bandcamp workflow

### ISSUE THREAD

**Issue by 89z** [hisaac/hisaac.net#14]
Do you have the sourcecode for the workflow described here:

https://hisaac.net/2016/10/09/deep-linking-in-the-bandcamp-ios-app.html

**Comment by hisaac** [comment]
Not any source code per-se, but there are links to download the workflows to your phone near the bottom of the article. Here they are for convenience:

- [Open current Bandcamp web page in Bandcamp iOS app](https://workflow.is/workflows/bd3284f7333e406b87a4500230016ba5)
- [Open current Bandcamp web page in Bandcamp iOS app, and start playing the album (using the &play modifier from the original URI)](https://workflow.is/workflows/162f55c816e84cd59624c68e3e95409a)

Hope that helps!

**Comment by 89z** [comment]
yeah, I would like the source code for those workflows if possible. When I click on the links, it just takes me to a "Open in Bandcamp" page. I would like the code that makes it work, if possible. Did you lose it?

**Comment by hisaac** [comment]
I apologize, but I don't follow you. I don't think it's possible to access the actual source code of a Shortcut.

Here's what happens when I tap on the links on my iPhone:

https://user-images.githubusercontent.com/923876/151731402-85c2e123-ea41-4086-8cd3-38d7ca37ce61.MOV

Is that not what you see? Once you've added it to your shortcuts, you can open it and view the steps in the shortcut.

**Comment by 89z** [comment]
I dont have iOS, so I have no idea what you are talking about. I just want to port whatever you did to another language. However its not clear how you created these "programs" or "shortcuts" or whatever, because I dont see any code for what you created.

**Comment by hisaac** [comment]
Ah ok. Yeah, these are iOS-specific "shortcuts" they're called. It's not really code, it's a way to string together actions to perform little tasks.

**Comment by 89z** [comment]
Looking at it some more, it seems what you did is pretty hacky. I guess thats the only option, as it seems that even the official app doesnt have mobile deep linking. If you go into app settings, the app doesnt seem to recognize any bandcamp URLs. For the Android app anyway, not use about iOS.

**Comment by hisaac** [comment]
Definitely hacky 😅 Sadly, hacky is the only way I could get it to work. Without official support from Bandcamp, we're stuck.
